"""Local CLI configuration and safe first-run initialization."""

from __future__ import annotations

import json
import os
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from src.config.env import resolve_env

CONFIG_VERSION = 1
CONFIG_ENV = "NOESIS_CONFIG"
LEGACY_CONFIG_ENV = "NEURONEWS_CONFIG"

_DEFAULT_DOMAINS = """# Generated by `noesis init`; edit to add public domains.
version: 1
domains:
  - name: local
    backing: corpus-view
    description: Private documents stored on this machine.
    embedding_model: all-MiniLM-L6-v2
    tags: [local, private]
    keywords: [meeting, decision, project, memo, research, transcript]
    embedding_anchors:
      - personal notes, private documents, project decisions, and correspondence
    feeds: []
"""


class ConfigError(RuntimeError):
    """A local configuration is absent, invalid, or unsafe."""


@dataclass(frozen=True)
class RuntimeConfig:
    path: Path
    root: Path
    warehouse: Path
    domains: Path
    cursor_directory: Path
    principal: str
    api_host: str
    api_port: int
    mcp_host: str
    mcp_port: int

    def public_dict(self) -> dict[str, Any]:
        return {
            "config_version": CONFIG_VERSION,
            "config_path": str(self.path),
            "root": str(self.root),
            "warehouse": str(self.warehouse),
            "domains": str(self.domains),
            "cursor_directory": str(self.cursor_directory),
            "principal": self.principal,
            "api": {"host": self.api_host, "port": self.api_port},
            "mcp": {"host": self.mcp_host, "port": self.mcp_port},
        }


def default_config_path() -> Path:
    configured = resolve_env("CONFIG")
    return (
        Path(configured).expanduser()
        if configured
        else Path.cwd() / ".noesis/config.json"
    )


def _absolute(value: Any, base: Path, field: str) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty path")
    path = Path(value).expanduser()
    return (base / path).resolve() if not path.is_absolute() else path.resolve()


def _port(value: Any, field: str) -> int:
    try:
        result = int(value)
    except (TypeError, ValueError) as exc:
        raise ConfigError(f"{field} must be an integer") from exc
    if not 1 <= result <= 65535:
        raise ConfigError(f"{field} must be between 1 and 65535")
    return result


def validate_config(payload: Any, path: Path) -> RuntimeConfig:
    if not isinstance(payload, dict):
        raise ConfigError("configuration must be a JSON object")
    if payload.get("config_version") != CONFIG_VERSION:
        raise ConfigError(
            f"unsupported config_version {payload.get('config_version')!r}; expected 1"
        )
    base = path.resolve().parent
    root = _absolute(payload.get("root", "."), base, "root")
    principal = str(payload.get("principal") or "").strip()
    if not principal or len(principal) > 200:
        raise ConfigError("principal must contain 1 to 200 characters")
    api = payload.get("api") or {}
    mcp = payload.get("mcp") or {}
    if not isinstance(api, dict) or not isinstance(mcp, dict):
        raise ConfigError("api and mcp settings must be objects")
    return RuntimeConfig(
        path=path.resolve(),
        root=root,
        warehouse=_absolute(payload.get("warehouse"), base, "warehouse"),
        domains=_absolute(payload.get("domains"), base, "domains"),
        cursor_directory=_absolute(
            payload.get("cursor_directory"), base, "cursor_directory"
        ),
        principal=principal,
        api_host=str(api.get("host") or "127.0.0.1"),
        api_port=_port(api.get("port", 8000), "api.port"),
        mcp_host=str(mcp.get("host") or "127.0.0.1"),
        mcp_port=_port(mcp.get("port", 8100), "mcp.port"),
    )


def load_config(path: Path | None = None) -> RuntimeConfig:
    location = (path or default_config_path()).expanduser().resolve()
    if not location.is_file():
        raise ConfigError(f"configuration not found at {location}; run `noesis init`")
    try:
        payload = json.loads(location.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ConfigError(f"could not read configuration {location}: {exc}") from exc
    config = validate_config(payload, location)
    if not config.domains.is_file():
        raise ConfigError(f"domain configuration not found at {config.domains}")
    return config


def initialize(
    *, config_path: Path | None = None, root: Path | None = None
) -> tuple[RuntimeConfig, dict[str, Any]]:
    """Create a private local workspace without overwriting existing files."""
    location = (
        config_path.expanduser().resolve()
        if config_path is not None
        else ((root or Path.cwd() / ".noesis") / "config.json").expanduser().resolve()
    )
    if location.exists():
        config = load_config(location)
        return config, {"created": [], "preserved": [str(location)]}

    workspace = root.expanduser().resolve() if root else location.parent
    domains = workspace / "domains.yml"
    warehouse = workspace / "data/noesis.duckdb"
    cursors = workspace / "cursors"
    created: list[str] = []
    preserved: list[str] = []
    workspace.mkdir(parents=True, exist_ok=True)
    warehouse.parent.mkdir(parents=True, exist_ok=True)
    cursors.mkdir(parents=True, exist_ok=True)
    if domains.exists():
        preserved.append(str(domains))
    else:
        domains.write_text(_DEFAULT_DOMAINS, encoding="utf-8")
        created.append(str(domains))

    payload = {
        "config_version": CONFIG_VERSION,
        "root": str(workspace),
        "warehouse": str(warehouse),
        "domains": str(domains),
        "cursor_directory": str(cursors),
        "principal": "local-user",
        "api": {"host": "127.0.0.1", "port": 8000},
        "mcp": {"host": "127.0.0.1", "port": 8100},
    }
    config = validate_config(payload, location)

    from src.kb.registry import load_registry

    load_registry(domains)
    import duckdb

    from src.database.local_warehouse_seed import ensure_schema
    from src.kb.membership import run_membership_pass
    from src.kb.watches import grant_watch_domain

    conn = duckdb.connect(str(warehouse))
    try:
        ensure_schema(conn)
        registry = load_registry(domains)
        run_membership_pass(conn, registry)
        for definition in registry.domains():
            if "private" in {tag.casefold() for tag in definition.tags}:
                grant_watch_domain(conn, payload["principal"], definition.name)
    finally:
        conn.close()
    os.chmod(warehouse, stat.S_IRUSR | stat.S_IWUSR)
    location.parent.mkdir(parents=True, exist_ok=True)
    with location.open("x", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
    os.chmod(location, stat.S_IRUSR | stat.S_IWUSR)
    created.extend([str(warehouse), str(location), str(cursors)])
    return config, {"created": created, "preserved": preserved}


def open_warehouse(config: RuntimeConfig):
    import duckdb

    config.warehouse.parent.mkdir(parents=True, exist_ok=True)
    return duckdb.connect(str(config.warehouse))


__all__ = [
    "CONFIG_ENV",
    "CONFIG_VERSION",
    "ConfigError",
    "RuntimeConfig",
    "default_config_path",
    "initialize",
    "load_config",
    "open_warehouse",
    "validate_config",
]
